Change chef downloads url
chef/supermarket pull request #2449
Opened 2021-12-17 12:33 UTC by manick-vel-11

Signed-off-by: Manick Vel <mkumaravel@msystechnologies.com>

### Description

Change chef downloads url from downloads.chef.io to https://www.chef.io/downloads

### Issues Resolved
https://github.com/chef/supermarket/issues/2350

### Check List

- [x] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2021-12-17 14:55 UTC, msys-sgarg commented
LGTM

2021-12-20 05:51 UTC, dheerajd-msys approved these changes

2021-12-29 23:08 UTC, tas50 requested changes
make sure we get the www. in there as well

2021-12-30 17:27 UTC, dheerajd-msys approved these changes

2021-12-30 17:53 UTC, merged